name: Restore LLVM tree
description: Restore LLVM tree from artifact

inputs:
  patch-path:
    description: Path to be used to clone patches
    required: true
  patch-ref:
    description: Explicit upstream ref of patch collection
    required: true
  config-name:
    description: Build configuration name
    required: true
  cygwin-root:
    description: Cygwih root path
    required: true
  artifact-ids:
    description: IDs to restore artifact, comma-separated
    required: true
  use-cache-name:
    description: Stage1 cache name
    required: false
  use-profile:
    description: Proflie name to be used with PGO
    required: false

runs:
  using: "composite"
  steps:
    - name: prepare patches
      id: checkout-patch
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: ${{ inputs.patch-path }}
        ref: ${{ inputs.patch-ref }}

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        artifact-ids: ${{ inputs.artifact-ids }}
        merge-multiple: true

    - id: cache-restore
      if: ${{ inputs.use-cache-name != '' }}
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        fail-on-cache-miss: true
        enableCrossOsArchive: true
        key: ${{ inputs.use-cache-name }}
        restore-keys: ${{ inputs.use-cache-name }}
        path: 'package-*.tar'

    - id: profile-restore
      if: ${{ inputs.use-profile != '' }}
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        enableCrossOsArchive: true
        key: profiledata-${{ inputs.use-profile }}
        restore-keys: profiledata-${{ inputs.use-profile }}
        path: ${{ inputs.use-profile }}.profdata

    - id: check-profile
      if: ${{ inputs.use-profile != '' && ! steps.profile-restore.outputs.cache-hit }}
      env:
        PROFILE: ${{ inputs.use-profile }}
      run: |
        echo "::warning ::profile data '$PROFILE' is not found"
      shell: bash

    - name: unpack artifacts
      env:
        CYGWIN_ROOT: ${{ inputs.cygwin-root }}
      run: |
        if [ "$RUNNER_OS" == Windows ] && [ -n "$CYGWIN_ROOT" ]; then
          set +h
          pushd "$CYGWIN_ROOT" > /dev/null
          cd bin
          export PATH=$PWD:$PATH
          popd > /dev/null
        fi

        for f in *.tar; do
          echo extracting $f
          if [[ $f = package-*.tar ]]; then
            mkdir -p llvm-stage1
            cd llvm-stage1
            tar -xf ../$f --strip-components=1
            cd ..
          else
            tar -xf $f
          fi
          rm $f
        done
      shell: bash

