name: Restore LLVM tree
description: Restore LLVM tree from artifact

inputs:
  patch-path:
    description: Path to be used to clone patches
    required: true
  patch-ref:
    description: Explicit upstream ref of patch collection
    required: true
  config-name:
    description: Build configuration name
    required: true
  cygwin-root:
    description: Cygwih root path
    required: true
  artifact-ids:
    description: IDs to restore artifact, comma-separated
    required: true

runs:
  using: "composite"
  steps:
    - name: prepare patches
      id: checkout-patch
      uses: actions/checkout@v5
      with:
        path: ${{ inputs.patch-path }}
        ref: ${{ inputs.patch-ref }}

    - uses: actions/download-artifact@v5
      with:
        artifact-ids: ${{ inputs.artifact-ids }}
        merge-multiple: true

    - name: unpack artifacts
      env:
        CYGWIN_ROOT: ${{ inputs.cygwin-root }}
      run: |
        if [ "$RUNNER_OS" == Windows ] && [ -n "$CYGWIN_ROOT" ]; then
          set +h
          pushd "$CYGWIN_ROOT" > /dev/null
          cd bin
          export PATH=$PWD:$PATH
          popd > /dev/null
        fi

        for f in *.tar; do
          echo extracting $f
          tar xf $f
          rm $f
        done
        if type rebase 2> /dev/null; then
          find . -name '*.dll' | xargs rebase -O || true
        fi
      shell: bash

