name: Restore LLVM tree
description: Restore LLVM tree from artifact

inputs:
  patch-path:
    description: Path to be used to clone patches
    required: true
  patch-ref:
    description: Explicit upstream ref of patch collection
    required: true
  config-name:
    description: Build configuration name
    required: true
  cygwin-root:
    description: Cygwih root path
    required: true
  artifact-ids:
    description: IDs to restore artifact, comma-separated
    required: true
  use-cache-name:
    description: Stage1 cache name
    required: false

runs:
  using: "composite"
  steps:
    - name: prepare patches
      id: checkout-patch
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        path: ${{ inputs.patch-path }}
        ref: ${{ inputs.patch-ref }}

    - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        artifact-ids: ${{ inputs.artifact-ids }}
        merge-multiple: true

    - id: cache-restore
      if: ${{ inputs.use-cache-name != '' }}
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        fail-on-cache-miss: true
        enableCrossOsArchive: true
        key: ${{ inputs.use-cache-name }}
        restore-keys: ${{ inputs.use-cache-name }}
        path: 'package-*.tar'

    - name: unpack artifacts
      env:
        CYGWIN_ROOT: ${{ inputs.cygwin-root }}
      run: |
        if [ "$RUNNER_OS" == Windows ] && [ -n "$CYGWIN_ROOT" ]; then
          set +h
          pushd "$CYGWIN_ROOT" > /dev/null
          cd bin
          export PATH=$PWD:$PATH
          popd > /dev/null
        fi

        for f in *.tar; do
          echo extracting $f
          if [[ $f = package-*.tar ]]; then
            mkdir -p llvm-stage1
            cd llvm-stage1
            tar -xf ../$f --strip-components=1
            cd ..
          else
            tar -xf $f
          fi
          rm $f
        done
      shell: bash

