name: Build LLVM
description: Build patched LLVM

inputs:
  llvm-path:
    description: Path to source tree
    required: true
  patch-path:
    description: Path to be used to clone patches
    required: true
  config-name:
    description: Build configuration name
    required: true
  cygwin-root:
    description: Cygwih root path
    reuqired: true
  build-project:
    description: Project root to build, relative to llvm-project
    required: true
  build-target:
    description: Target name to build, which is passed to ninja
    required: false
    default: ''
  check-target:
    description: Name to existence check for running testsuite, returned in check-target
    required: false
    default: ''
  build-name:
    description: Build name suffix
    required: true
  extra-lit-opts:
    description: LIT_OPTS
    required: false
  install-prefix:
    description: PREFIX
    required: false
    default: '/'
  artifact-suffix:
    description: Additional suffix to artifact name
    required: false
    default: ''
  save-instrument:
    description: Type of profile data to be saved
    required: false
    default: ''
  build-retention-days:
    required: false
    default: 0
  install-retention-days:
    required: false
    default: 0

outputs:
  build-name:
    description: Build identifier name
    value: ${{ inputs.build-project }}-${{ inputs.build-name }}
  build-artifact:
    description: ID of the uploaded build artifact
    value: ${{ steps.upload-build.outputs.artifact-id }}
  log-artifact:
    description: ID of the uploaded build-log artifact
    value: ${{ steps.upload-log.outputs.artifact-id }}
  install-artifact:
    description: ID of the uploaded install artifact
    value: ${{ steps.upload-install.outputs.artifact-id }}
  check-target:
    description: Target name to run tests
    value: ${{ steps.check-check.outputs.target-name }}

runs:
  using: "composite"
  steps:
    - id: build
      name: build ${{ inputs.build-project }} ${{ inputs.config-name }}
      env:
        BUILD_NAME: ${{ inputs.build-name }}
        BUILD_TARGET: ${{ inputs.build-target || 'all' }}
        CONFIG_NAME: ${{ inputs.config-name }}
        CYGWIN_ROOT: ${{ inputs.cygwin-root }}
        BUILD_PROJECT: ${{ inputs.build-project }}
        LLVM_PATH: ${{ inputs.llvm-path }}
        PATCH_PATH: ${{ inputs.patch-path }}
        EXTRA_LIT_OPTS: ${{ inputs.extra-lit-opts }}
        SAVE_INSTRUMENT: ${{ inputs.save-instrument }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        ## Config, Build, Test
        . "$ACTION_PATH/do_build.sh"
      shell: bash

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ inputs.save-instrument }}
      id: upload-instrument
      with:
        name: profiledata-${{ inputs.config-name }}
        overwrite: true
        path: ${{ inputs.config-name }}.profdata

    - id: save-instrument
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: ${{ inputs.save-instrument }}
      with:
        key: profiledata-${{ inputs.config-name }}-${{ steps.upload-instrument.outputs.artifact-id }}
        enableCrossOsArchive: true
        path: ${{ inputs.config-name }}.profdata

    - id: check-check
      env:
        BUILD_NAME: ${{ inputs.build-name }}
        BUILD_TARGET: ${{ inputs.build-target || 'all' }}
        BUILD_PROJECT: ${{ inputs.build-project }}
        CHECK_TARGET: ${{ inputs.check-target }}
      run: |
        . '${{ github.action_path }}/source_cygpath'
        b="build-$BUILD_PROJECT-$BUILD_NAME"
        t="${CHECK_TARGET:-check-${BUILD_TARGET%%,*}}"
        if ninja -C "$b" -t query "$t" > /dev/null 2>&1 && ! grep -q '^LLVM_LIT_ARGS:STRING=.*--version' "$b/CMakeCache.txt"
        then
          echo "target-name=$t" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - id: archive-builds
      if: ${{ always() && inputs.build-retention-days >= 0 }}
      name: archive builds ${{ inputs.build-project }} ${{ inputs.config-name }}
      env:
        BUILD_NAME: ${{ inputs.build-name }}
        BUILD_PROJECT: ${{ inputs.build-project }}
        CYGWIN_ROOT: ${{ inputs.cygwin-root }}
      run: |
        . '${{ github.action_path }}/source_cygpath'
        tar -cf build-$BUILD_PROJECT-$BUILD_NAME.tar --ignore-failed-read build-$BUILD_PROJECT-$BUILD_NAME
      shell: bash

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ always() && inputs.build-retention-days >= 0 }}
      id: upload-build
      with:
        name: build-artifact-${{ inputs.build-project }}-${{ inputs.build-target || 'all' }}-${{ inputs.config-name }}${{ inputs.artifact-suffix }}
        overwrite: true
        path: build-${{ inputs.build-project }}-${{ inputs.build-name }}.tar
        retention-days: ${{ inputs.build-retention-days }}

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ always() }}
      id: upload-log
      with:
        name: build-log-${{ inputs.build-project }}-${{ inputs.build-target || 'all' }}-${{ inputs.config-name }}${{ inputs.artifact-suffix }}
        overwrite: true
        path: |
          buildlog-*.txt
          configlog-*.txt
          env-*.txt

    - id: install
      if: ${{ inputs.install-prefix != '/' && inputs.install-retention-days >= 0 }}
      name: install ${{ inputs.build-project }} ${{ inputs.config-name }}
      env:
        BUILD_NAME: ${{ inputs.build-name }}
        BUILD_PROJECT: ${{ inputs.build-project }}
        INSTALL_PREFIX: ${{ inputs.install-prefix }}
        CYGWIN_ROOT: ${{ inputs.cygwin-root }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        ## Install
        . "$ACTION_PATH/do_build.sh"
      shell: bash

    - id: archive-installs
      if: ${{ always() && inputs.install-prefix != '/' && inputs.install-retention-days >= 0 }}
      name: archive installs ${{ inputs.build-project }} ${{ inputs.config-name }}
      env:
        BUILD_NAME: ${{ inputs.build-name }}
        BUILD_PROJECT: ${{ inputs.build-project }}
        CYGWIN_ROOT: ${{ inputs.cygwin-root }}
      run: |
        . '${{ github.action_path }}/source_cygpath'
        cd install
        find . -name '*.dll' | xargs -r chmod +x
        tar -cf ../package-$BUILD_PROJECT-$BUILD_NAME.tar *
        cd ..
      shell: bash

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ inputs.install-prefix != '/' && inputs.install-retention-days >= 0 }}
      id: upload-install
      with:
        name: package-${{ inputs.build-project }}-${{ inputs.config-name }}${{ inputs.artifact-suffix }}
        path: package-${{ inputs.build-project }}-${{ inputs.build-name }}.tar
        retention-days: ${{ inputs.install-retention-days }}
