#!/bin/bash

pathenv() { true; }
[ "$(uname -o)" = "Msys" ] || return 0
[ -n "$CYGWIN_ROOT" ] || return 0
MSYS_NO_PATHCONV=1 msyscygpath=/bin/cygpath
MSYS_NO_PATHCONV=1 [ -x $msyscygpath ] || return 0
MSYS_NO_PATHCONV=1 cygcygpath="$($msyscygpath -ua "$CYGWIN_ROOT")/bin/cygpath"
MSYS_NO_PATHCONV=1 [ -x $cygcygpath ] || return 0

pathenv() {
  local v
  while read; do
    for e in "$@"; do
      if [ "$REPLY" = "$e" ] && [ -n "${!REPLY}" ]; then
        MSYS_NO_PATHCONV=1 v="$(MSYS_NO_PATHCONV=1 PATH="$($msyscygpath -ua "$CYGWIN_ROOT")/bin:$PATH" "$cygcygpath" -u "$(MSYS_NO_PATHCONV=1 "$msyscygpath" -w "${!e}")")"
        MSYS_NO_PATHCONV=1 eval "$REPLY='$v'"
      fi
    done
  done < <(env -0 | sed -z 's/=.*$/\n/')
  unset v
}
pathenv "$@"
