name: Build LLVM with libc++ Cygwin binaries with patches
on:
  schedule:
    - cron: '18 11 * * *'
  workflow_dispatch:

jobs:
  build-stage0:
    uses: ./.github/workflows/build-llvm.yml
    with:
      config-name: linux-fullpatch
      install-prefix: 'stage0'
      build-retention-days: -1

  build-stage1:
    needs: build-stage0
    uses: ./.github/workflows/build-llvm.yml
    with:
      config-name: cross-fullpatch
      build-name: ${{ needs.build-stage0.outputs.build-name }}
      patch-commit: ${{ needs.build-stage0.outputs.patch-commit }}
      source-artifact: ${{ needs.build-stage0.outputs.source-artifact }}
      prereq-artifacts: ${{ needs.build-stage0.outputs.install-artifacts }}
      install-prefix: 'stage1'
      stage1-bindir: 'stage0/bin'
      build-retention-days: -1

  build-stage2:
    needs: build-stage1
    uses: ./.github/workflows/build-llvm.yml
    with:
      config-name: cygwin-fullpatch
      build-name: ${{ needs.build-stage1.outputs.build-name }}
      patch-commit: ${{ needs.build-stage1.outputs.patch-commit }}
      source-artifact: ${{ needs.build-stage1.outputs.source-artifact }}
      prereq-artifacts: ${{ needs.build-stage1.outputs.install-artifacts }}
      install-prefix: ''
      stage1-bindir: 'stage1/bin'
