name: Build LLVM multistage
on:
  #schedule:
  #  - cron: '18 22 * * *'
  workflow_dispatch:
    inputs:
      upstream-branch:
        description: 'Upstream branch to build'
        type: string
        required: false
        default: 'main'
      patch-series:
        description: 'Patch series to apply'
        type: string
        required: false
        default: 'main'

jobs:
  select:
    runs-on: ubuntu-latest
    name: Select target

    outputs:
      config-name: 'cygwin-dylib'
      patch-path: 'patches'
      llvm-path: 'llvm-project'
      upstream-branch: ${{ inputs.patch-series || inputs.upstream-branch || 'main' }}
      build-name: ${{ steps.prepare-tree.outputs.build-name }}
      upstream-commit: ${{ steps.prepare-tree.outputs.upstream-commit }}
      patch-commit: ${{ steps.prepare-tree.outputs.patch-commit }}
      source-artifact: ${{ steps.prepare-tree.outputs.source-artifact }}

    steps:
      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare build tree
        id: prepare-tree
        uses: ./self/.github/actions/prepare-llvm-tree
        with:
          llvm-path: 'llvm-project'
          remote-ref: ${{ inputs.upstream-branch || 'main' }}
          patch-path: 'patches'
          patch-ref: ''
          patch-series: ${{ inputs.patch-series || inputs.upstream-branch || 'main' }}
          cygwin-root: ''

  build-llvm:
    runs-on: windows-latest
    needs: select
    name: Build LLVM ${{ needs.select.outputs.upstream-branch }}

    outputs:
      artifacts: ${{ needs.select.outputs.source-artifact }},${{ steps.build.outputs.build-artifact }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          config-name: ${{ needs.select.outputs.config-name }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.select.outputs.source-artifact }}

      - name: build llvm
        id: build
        uses: ./self/.github/actions/build-llvm-2
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: llvm
          build-name: ${{ needs.select.outputs.build-name }}
          parallel-compile-jobs: 3
          install-prefix: install

  check-llvm:
    runs-on: windows-latest
    needs: [select, build-llvm]
    name: Check LLVM ${{ needs.select.outputs.upstream-branch }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          config-name: ${{ needs.select.outputs.config-name }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.build-llvm.outputs.artifacts }}

      - name: check llvm
        id: check
        uses: ./self/.github/actions/build-llvm-2
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: llvm
          build-target: check-all
          build-name: ${{ needs.select.outputs.build-name }}

  build-clang:
    runs-on: windows-latest
    needs: [select, build-llvm]
    name: Build Clang ${{ needs.select.outputs.upstream-branch }}

    outputs:
      artifacts: ${{ needs.build-llvm.outputs.artifacts }},${{ steps.build.outputs.build-artifact }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.build-llvm.outputs.artifacts }}

      - name: build clang
        id: build
        uses: ./self/.github/actions/build-llvm-2
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: clang
          build-name: ${{ needs.select.outputs.build-name }}
          parallel-compile-jobs: 3
          install-prefix: install

  check-clang:
    runs-on: windows-latest
    needs: [select, build-clang]
    name: Check Clang ${{ needs.select.outputs.upstream-branch }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          config-name: ${{ needs.select.outputs.config-name }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.build-clang.outputs.artifacts }}

      - name: check clang
        id: check
        uses: ./self/.github/actions/build-llvm-2
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: clang
          build-target: check-all
          build-name: ${{ needs.select.outputs.build-name }}

  build-lld:
    runs-on: windows-latest
    needs: [select, build-llvm]
    name: Build LLD ${{ needs.select.outputs.upstream-branch }}

    outputs:
      artifacts: ${{ needs.build-llvm.outputs.artifacts }},${{ steps.build.outputs.build-artifact }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          config-name: ${{ needs.select.outputs.config-name }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.build-llvm.outputs.artifacts }}

      - name: build lld
        id: build
        uses: ./self/.github/actions/build-llvm-2
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: lld
          build-name: ${{ needs.select.outputs.build-name }}
          parallel-compile-jobs: 3
          install-prefix: install

  check-lld:
    runs-on: windows-latest
    needs: [select, build-lld]
    name: Check LLD ${{ needs.select.outputs.upstream-branch }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          config-name: ${{ needs.select.outputs.config-name }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.build-lld.outputs.artifacts }}

      - name: check lld
        id: check
        uses: ./self/.github/actions/build-llvm-2
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: lld
          build-target: check-lld
          build-name: ${{ needs.select.outputs.build-name }}
