name: Build LLVM Cygwin binary with patches
on:
  schedule:
    - cron: '18 22 * * *'
  workflow_dispatch:
    inputs:
      config-name:
        description: 'Build config name'
        type: string
        required: false
        default: ''
  workflow_call:
    inputs:
      config-name:
        description: 'Build config name'
        type: string
        required: false
        default: ''
    outputs:
      config-name:
        value: ${{ jobs.select.outputs.config-name }}
      patch-path:
        value: ${{ jobs.select.outputs.patch-path }}
      patch-commit:
        value: ${{ jobs.select.outputs.patch-commit }}
      build-name:
        value: ${{ jobs.select.outputs.build-name }}
      source-artifact:
        value: ${{ jobs.select.outputs.source-artifact }}

jobs:
  select:
    runs-on: ubuntu-latest
    name: Select target

    outputs:
      patch-path: 'patches'
      llvm-path: 'llvm-project'
      config-name: ${{ inputs.config-name || 'cygwin-dylib' }}
      upstream-branch: ${{ steps.config.outputs.upstream-branch }}
      build-host: ${{ steps.config.outputs.build-host }}
      enable-llvm: ${{ steps.config.outputs.enable-llvm }}
      disable-llvm-test: ${{ steps.config.outputs.disable-llvm-test }}
      enable-clang: ${{ steps.config.outputs.enable-clang }}
      disable-clang-test: ${{ steps.config.outputs.disable-clang-test }}
      enable-lld: ${{ steps.config.outputs.enable-lld }}
      disable-lld-test: ${{ steps.config.outputs.disable-lld-test }}
      build-name: ${{ steps.prepare-tree.outputs.build-name }}
      upstream-commit: ${{ steps.prepare-tree.outputs.upstream-commit }}
      patch-commit: ${{ steps.prepare-tree.outputs.patch-commit }}
      source-artifact: ${{ steps.prepare-tree.outputs.source-artifact }}

    steps:
      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - run: cat "self/config/$CONFIG_NAME/conf.txt" >> "$GITHUB_OUTPUT"
        env:
          CONFIG_NAME: ${{ inputs.config-name || 'cygwin-dylib' }}
        id: config

      - name: prepare build tree
        id: prepare-tree
        uses: ./self/.github/actions/prepare-llvm-tree
        with:
          llvm-path: 'llvm-project'
          remote-ref: ${{ steps.config.outputs.upstream-branch }}
          patch-path: 'patches'
          patch-ref: ''
          patch-series: ${{ steps.config.outputs.patch-series }}
          cygwin-root: ''

  build-llvm:
    needs: select
    runs-on: ${{ needs.select.outputs.build-host }}
    if: ${{ needs.select.outputs.enable-llvm }}
    name: Build LLVM ${{ needs.select.outputs.upstream-branch }}

    outputs:
      artifacts: ${{ needs.select.outputs.source-artifact }},${{ steps.build.outputs.build-artifact }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          config-name: ${{ needs.select.outputs.config-name }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.select.outputs.source-artifact }}

      - name: build llvm
        id: build
        uses: ./self/.github/actions/build-llvm
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: llvm
          build-name: ${{ needs.select.outputs.build-name }}
          parallel-compile-jobs: 3
          install-prefix: install

  check-llvm:
    needs: [select, build-llvm]
    runs-on: ${{ needs.select.outputs.build-host }}
    if: ${{ ! needs.select.outputs.disable-llvm-test }}
    name: Check LLVM ${{ needs.select.outputs.upstream-branch }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          config-name: ${{ needs.select.outputs.config-name }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.build-llvm.outputs.artifacts }}

      - name: check llvm
        id: check
        uses: ./self/.github/actions/build-llvm
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: llvm
          build-target: check-all
          build-name: ${{ needs.select.outputs.build-name }}

  build-clang:
    needs: [select, build-llvm]
    runs-on: ${{ needs.select.outputs.build-host }}
    if: ${{ needs.select.outputs.enable-clang }}
    name: Build Clang ${{ needs.select.outputs.upstream-branch }}

    outputs:
      artifacts: ${{ needs.build-llvm.outputs.artifacts }},${{ steps.build.outputs.build-artifact }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.build-llvm.outputs.artifacts }}

      - name: build clang
        id: build
        uses: ./self/.github/actions/build-llvm
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: clang
          build-name: ${{ needs.select.outputs.build-name }}
          parallel-compile-jobs: 3
          install-prefix: install

  check-clang:
    needs: [select, build-clang]
    runs-on: ${{ needs.select.outputs.build-host }}
    if: ${{ ! needs.select.outputs.disable-clang-test }}
    name: Check Clang ${{ needs.select.outputs.upstream-branch }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          config-name: ${{ needs.select.outputs.config-name }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.build-clang.outputs.artifacts }}

      - name: check clang
        id: check
        uses: ./self/.github/actions/build-llvm
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: clang
          build-target: check-all
          build-name: ${{ needs.select.outputs.build-name }}

  build-lld:
    needs: [select, build-llvm]
    runs-on: ${{ needs.select.outputs.build-host }}
    if: ${{ needs.select.outputs.enable-lld }}
    name: Build LLD ${{ needs.select.outputs.upstream-branch }}

    outputs:
      artifacts: ${{ needs.build-llvm.outputs.artifacts }},${{ steps.build.outputs.build-artifact }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          config-name: ${{ needs.select.outputs.config-name }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.build-llvm.outputs.artifacts }}

      - name: build lld
        id: build
        uses: ./self/.github/actions/build-llvm
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: lld
          build-name: ${{ needs.select.outputs.build-name }}
          parallel-compile-jobs: 3
          install-prefix: install

  check-lld:
    needs: [select, build-lld]
    runs-on: ${{ needs.select.outputs.build-host }}
    if: ${{ ! needs.select.outputs.disable-lld-test }}
    name: Check LLD ${{ needs.select.outputs.upstream-branch }}

    steps:
      - run: git config --global core.autocrlf input

      - name: prepare patches
        id: checkout-self
        uses: actions/checkout@v5
        with:
          path: self

      - name: prepare Cygwin
        id: prepare-cygwin
        uses: ./self/.github/actions/prepare-cygwin-root

      - name: restore build tree
        id: prepare-tree
        uses: ./self/.github/actions/restore-llvm-tree
        with:
          config-name: ${{ needs.select.outputs.config-name }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          patch-ref: ${{ needs.select.outputs.patch-commit }}
          build-name: ${{ needs.select.outputs.build-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          artifact-ids: ${{ needs.build-lld.outputs.artifacts }}

      - name: check lld
        id: check
        uses: ./self/.github/actions/build-llvm
        with:
          llvm-path: ${{ needs.select.outputs.llvm-path }}
          patch-path: ${{ needs.select.outputs.patch-path }}
          config-name: ${{ needs.select.outputs.config-name }}
          cygwin-root: ${{ steps.prepare-cygwin.outputs.root }}
          build-project: lld
          build-target: check-lld
          build-name: ${{ needs.select.outputs.build-name }}
