name: Construct Cygwin Filesystem
on:
  workflow_dispatch:

jobs:
  do-update:
    runs-on: windows-latest
    concurrency:
      group: construct-cygwin

    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: update Cygwin
        id: cygwin
        uses: ./.github/actions/prepare-cygwin-root
        with:
          skip-update: false
          allow-test-packages: false
      - name: show packages
        run: |
          ${{ steps.cygwin.outputs.root }}\bin\cat.exe /etc/setup/installed.db
        shell: cmd
